name: Fix Code Formatting

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  auto_fix:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt

      - name: Run isort and black auto-fix
        run: |
          isort .
          black .

      - name: Commit and push fixes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Formated code with isort and black"
            git push
          fi
